### ISSUE TITLE
data errors on PURE

### ISSUE THREAD

**Issue by AdaQueen-wy** [broken-dream/FGCS#1]
hello，I encounter data errors when using your dataset to run PURE entity tasks. 
“TypeError: object of type 'bool' has no len()”
Do you have a processed dataset that can be directly run on Pure

**Comment by broken-dream** [comment]
We add a script for converting data to the PURE format. You can run it to generate data that meets the PURE format requirements.

**Comment by AdaQueen-wy** [comment]
Could you please give me the link to this script?

**Comment by AdaQueen-wy** [comment]
Your help was very useful！Thank you！
